theme: jekyll-theme-minimal
title: Project ADA-401
description: Datastory of team Pandamonium 
show_downloads: True
navigation:
  - title: Datastory
    url: README
  - title: Don't click here 
    url: example
