theme: jekyll-theme-minimal
title: Scripted Sisterhood
description: Project ADA by Pandamonium
show_downloads: True
navigation:
  - title: Main
    url: README.md
  - title: Don't click here 
    url: example
