theme: jekyll-theme-minimal
title: Scripted Sisterhood
description: Project ADA by Pandamonium
show_downloads: True
navigation:
  - title: See if it works
    url: README.md
  - title: Example
    url: example
